name: tritek_lms
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.2+1
  path_provider: ^1.6.24
  cupertino_icons: ^0.1.3
  carousel_slider: ^2.3.1
  dio: ^3.0.10
  rxdart: ^0.24.1
  font_awesome_flutter: ^8.10.0
  fluttertoast: ^7.1.4
  custom_radio: ^0.1.2
  flutter_rating_bar: ^3.2.0+1
  page_transition: ^1.1.7+2
  flutter_spinkit: ^4.1.2+1
  shared_preferences: ^0.5.12+4
  provider: ^4.3.2+2
  bubble_bottom_bar: ^1.2.0
  flutter_slidable: ^0.5.7
  chewie: ^0.9.10
  video_player: ^0.10.12
  bubble: ^1.1.9+1
  auto_size_text: ^2.1.0
  flutter_html: ^1.0.2
  intl_phone_number_input: ^0.5.2+2
  custom_switch:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

module:
  androidX: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
   - assets/icon.png
   - assets/user_profile/
   - assets/new_course/
   - assets/courses/
   - assets/json/
   - assets/payment_icon/
   - assets/onboarding/
   - assets/category/

  fonts:
    - family: Signika Negative
      fonts:
        - asset: fonts/signika_negative/SignikaNegative-Regular.ttf
        - asset: fonts/signika_negative/SignikaNegative-Bold.ttf
          weight: 700