name: tritek_lms
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.2+1
  floor: ^0.18.0
  connectivity: ^2.0.2
  data_connection_checker: ^0.3.4
  google_sign_in: ^4.5.6
  path_provider: ^1.6.24
  cupertino_icons: any
  carousel_slider: ^2.3.1
  dio: ^3.0.10
  rxdart: ^0.25.0
  fluttertoast: ^7.1.6
  flutter_rating_bar: ^3.2.0+1
  flutter_open_whatsapp: ^0.1.2
  page_transition: ^1.1.7+3
  flutter_spinkit: ^4.1.2+1
  shared_preferences: ^0.5.12+4
  flutter_secure_storage: ^3.3.5
  provider: ^4.3.2+3
  flutter_cache_manager: any
  share: ^0.6.5+4
  jiffy: ^3.0.1
  flutter_local_notifications: ^3.0.2
  flutter_native_timezone: ^1.0.4
  stripe_sdk: ^4.0.0
  flutter_staggered_grid_view: ^0.3.3
  intl: ^0.16.1
  flutter_inappwebview: ^4.0.0+4
  flutter_slidable: ^0.5.7
  bubble: ^1.1.9+1
  auto_size_text: ^2.1.0
  flutter_html: any
  email_validator: ^1.0.6
  image_picker: ^0.6.7+17
  custom_switch:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  floor_generator: ^0.18.0
  build_runner: ^1.10.11

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

module:
  androidX: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
   - assets/icon.png
   - assets/user_profile/
   - assets/payment_icon/

  fonts:
    - family: Signika Negative
      fonts:
        - asset: fonts/signika_negative/SignikaNegative-Regular.ttf
        - asset: fonts/signika_negative/SignikaNegative-Bold.ttf
          weight: 700